server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: iholin
    password: 3sotnibaksov
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

logging:
  level:
    org.springframework.security: debug
    org.springframework.security.oauth2.server.authorization: debug

app:
  security:
    issuer: http://localhost:8081
  keys:
    jks:
      location: classpath:keystore/pm-auth.jks
      password: changeit
      alias: pm-auth