spring:
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/authdb
    username: iholin
    password: 3sotnibaksov

app:
  security:
    issuer: http://pm-auth-server:8081
  keys:
    jks:
      location: classpath:keystore/pm-auth.jks
      password: 3sotnibaksov
      alias: pm-auth