spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: iholin
    password: 3sotnibaksov
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security.oauth2.server.authorization: info

app:
  security:
    issuer: http://localhost:8081
  keys:
    jks:
      location: classpath:keystore/pm-auth.jks
      password: 3sotnibaksov
      alias: pm-auth